name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1t7QYglTph4BdtHmA0HYkm2T5Ah_6uFkSgp1XoUsxUfjkpE3o
        USER_PASS: chen20081126
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 100h
